services:
  - type: web
    name: cernix
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: CERNIX
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: cernix-postgres
          property: connectionString
      - key: DB_URL
        fromDatabase:
          name: cernix-postgres
          property: connectionString
      - key: CACHE_STORE
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: public
      - key: CERNIX_DEMO_MODE
        value: "false"
      - key: REMITA_MERCHANT_ID
        sync: false
      - key: REMITA_API_KEY
        sync: false
      - key: REMITA_SERVICE_TYPE_ID
        sync: false
      - key: REMITA_BASE_URL
        sync: false
      - key: REMITA_PUBLIC_KEY
        sync: false
      - key: REMITA_SECRET_KEY
        sync: false
      - key: CERNIX_HMAC_KEY
        sync: false
      - key: CERNIX_ENCRYPTION_KEY
        sync: false

databases:
  - name: cernix-postgres
    databaseName: cernix
    user: cernix
    plan: starter
